version: 3.0.{build}

#environment:
#  APPVEYOR_USE_NUGET_EXE_FOR_PUBLISHING: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
  
test: off

deploy:
- provider: NuGet
  api_key:
    secure: VzDtwoWn8/ZRcndIQToQI61ElEWrROSEVjosi3W1MOUSIJgOjGYgHEZQC1eUVebH
#  skip_symbols: true
- provider: Environment
  name: nuget-appveyor

